on:
  push:
    branches:
      - master
  schedule:
    # https://crontab.guru/#00_21_*_*_0
    - cron: "00 21 * * 0"
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: tachiba/shopify-theme-kit-action@mater
        with:
          # Command
          shopify-command: version
          # Flags
          shopify-flags: -p=${{ secrets.SHOPIFY_PASSWORD }} -s=${{ secrets.SHOPIFY_STORE_URL }} -t=${{ secrets.SHOPIFY_THEME_ID }}
